### ISSUE TITLE
Reload Snippets On Change

### ISSUE THREAD

**Issue by frankdugan3** [rebornix/vscode-project-snippet#1]
First, great plugin. I've been wanting this for a long time!

User snippets are reloaded immediately when changed, but it seems that this plugin doesn't do that. I'm not really clear what triggers the reload, but I had to remove the project from Code and add it back in to get it to pick up the snippets files (even restarting VSCode didn't load the snippets). Any changes I make to the snippets are not picked up.

Any chance the files can be watched, or a command to reload snippets could be added to the command palette?

**Comment by rebornix** [comment]
@frankdugan3 monitoring changes can be the solution, thanks for your suggestion!

**Comment by rebornix** [comment]
@frankdugan3 0.2 is out and now you don't need to reload the window any more when you add new snippet files or make changes to the content. Thanks again, this is really useful.

**Comment by frankdugan3** [comment]
@rebornix Thank you, it works great!
