### ISSUE TITLE
powershell project-snippets not working

### ISSUE THREAD

**Issue by onutu** [rebornix/vscode-project-snippet#11]
Hello,

Powershell snippets having <$> special character right next to some text are not working correctly : 
    "SMO-Server": {
		"prefix": "SMO-Server",
		"body": [
			"$srv = New-Object Microsoft.SqlServer.Management.Smo.Server $Server"
		],
		"description": "Creates a SQL Server SMO Object"
	}
This snippet generates this line of code ($srv and $Server parameters are missing) : 
 = New-Object Microsoft.SqlServer.Management.Smo.Server 

Is there some kind of escaping that I'm missing, or maybe is there something wrong with my snippet ?

Thank's a lot for you help.

**Comment by rebornix** [comment]
@onutu hey, if you can share your code together with all the whitespaces (like tab, space) then I can do some checking locally, thanks!

**Comment by ericmacfarland** [comment]
What's the expected code output?
```
$srv = New-Object Microsoft.SqlServer.Management.Smo.Server $Server

# or

$<placeholder1> = New-Object Microsoft.SqlServer.Management.Smo.Server $<placeholder2>
```

Where `placeholders` are simple placeholders that can be tab navigated?

**Comment by ericmacfarland** [comment]
If you're looking for the final output to be have [placeholders](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_placeholders) for `srv` and `Server`, then can  then you can get it working with:
```
{
    "SMO-Server": {
        "prefix": "SMO-Server",
        "body": [
            "\\$${1:srv} = New-Object Microsoft.SqlServer.Management.Smo.Server \\$${2:Server}"
        ],
        "description": "Creates a SQL Server SMO Object"
    }
}
```
The user will be able to replace `srv` and `Server` in the normal tab-navigation fashion.

---

If you you're looking for the final output to be exactly `$srv = New-Object Microsoft.SqlServer.Management.Smo.Server $Server` then you can get it working with:
```
{
    "SMO-Server": {
        "prefix": "SMO-Server",
        "body": [
            "\\$srv = New-Object Microsoft.SqlServer.Management.Smo.Server \\$Server"
        ],
        "description": "Creates a SQL Server SMO Object"
    }
}
```

**Comment by onutu** [comment]
Hi @ericmacfarland , thanks for the 2 examples, that's exactly what I was looking for.
