### ISSUE TITLE
Snippets not appearing

### ISSUE THREAD

**Issue by RoystonS** [rebornix/vscode-project-snippet#19]
Hi, I'm using VS Code 1.25.1 on macOS.  I've taken some existing working snippets and put them into `.vscode/snippets/javascript.json`, `.vscode/snippets/javascriptreact.json`,`.vscode/snippets/typescript.json` and `.vscode/snippets/typescriptreact.json` files, and restarted VSCode, but none of the snippets appear either in tab completion or the explicit 'Insert snippet' command in various files I've tried.

Does this extension still work with VSCode 1.25.1?

**Comment by dheffx** [comment]
Same problem here.. also on VSCode 1.25.1 with macOS.

**Comment by RoystonS** [comment]
@dheffx Would it be possible for to you post a working example file (including filename) please? I still can't get this working at all...
