### ISSUE TITLE
Doesn't work?

### ISSUE THREAD

**Issue by unional** [rebornix/vscode-project-snippet#3]
I don't know why, it doesn't seem to work for me.

I follow the screenshot and put a json file as in `.vscode/snippets/javascript.json`.

I just copy my user snippets in there and clear my user snippet for testing.
It doesn't work.

I tried reloading vscode and it is still not working.

I also tried removing the comments as in the user snippet (as json technically does not support comments) and still it is not working.

**Comment by ollwenjones** [comment]
Same deal here. Went through exactly the same process, except I was using `typescript.json` and `typescriptreact.json`

**Comment by rebornix** [comment]
@ollwenjones @unional sorry for coming back too late. I'll give it a look, it's a valid one.

**Comment by rebornix** [comment]
@ollwenjones @unional do you mind sharing your snippet file for testing as right now what I found is if the json file contains comments, this extension fails silently while if I remove all comments, it works immediately.

**Comment by ollwenjones** [comment]
I removed comments from my `TypeScript React` user snippet, with no change to the behavior. I'm not seeing this fail, since it inserts the snippet, with multiple cursors, etc. It just has extra escape slashes before curly braces `\{` - I'm on Windows, if that makes a difference.

**Comment by rebornix** [comment]
I'm on macOS so maybe that's the trick, I should have a test on other platforms as well. Thanks for the info.

**Comment by ollwenjones** [comment]
@rebornix bah! I totally confused this with another issue on another plugin. :( Yes, it silently fails for me.

**Comment by ollwenjones** [comment]
I tried snippets without comments previously, but I can try again.

**Comment by rebornix** [comment]
@ollwenjones let me know if snippet without comments can work for you. If comment is the catch, I can come up with a solution to mitigate the issue.

**Comment by ollwenjones** [comment]
I took out all comments in project and user snippets, and still silently fails. Is the `.vscode/launch.json` pictured in the plugin home page important? What would go in there?

**Comment by rebornix** [comment]
@ollwenjones the launch file has nothing to do with this feature, now this issue is becoming weird. Do you have any public repo that I can play with to reproduce this problem?

**Comment by ollwenjones** [comment]
would the fact that I'm using typescript (versus javascript) make a difference?

**Comment by ollwenjones** [comment]
unfortunately this repo is private, but I can tell you I have
```shell
repo-root/
    ├─ .vscode/
    |   ├─ snippets/
    |   |   └─ typescript.json
    |   └─ settings.json
    └─ src/
        └─ <files I expect to use snippets>
```
### typescript.json:
```json
{
  "Copyright Statement": {
    "prefix": "copy",
    "body": [
      "..."
    ],
    "description": "Q-Free copyright statement"
  },

  "Arrow Operator": {
    "prefix": "aro",
    "body": [
      "($1) => {$2}"
    ],
    "description": "Creates arrow operator"
  }
}

```

**Comment by rebornix** [comment]
Sorry I'm stupid, I didn't take windows file path into account :( . Already push an update.

**Comment by ollwenjones** [comment]
> Sorry I'm stupid, I didn't take windows file path into account

No way - the most obvious thing is always the easiest to overlook. 😉  Thanks! 👍
