### ISSUE TITLE
Does not work when tabs are present in snippet body

### ISSUE THREAD

**Issue by geogauci** [rebornix/vscode-project-snippet#4]
I have installed this plugin in Visual Studio Code. I've created a new folder within vscode, snippets and created a typescript.json. I moved working snippets from my user's snippets to the local vscode snippets folder, and they did not work. After some investigation, it turns out that any tabs within the body will render the snippet unusable (when used from the vscode folder). Removing the tabs works fine.

**Comment by rebornix** [comment]
@geogauci do you mind sharing the minimal code snippet that fails on your machine? It would help me to troubleshoot with ease :)

**Comment by geogauci** [comment]
@rebornix, sure! 

`{
	"Snippet with spaces": {
		"prefix": "bit8-snippet-spaces",
		"body": [" This is correct "],
		"description": "Snippet with spaces (correct)"
	},
	"Snippet with tabs": {
		"prefix": "bit8-snippet-tabs",
		"body": ["	This	is	not	correct	"],
		"description": "Snippet with tabs (incorrect)"
	}
}`

Unless the second snippet is deleted, both snippets will not work.

**Comment by rebornix** [comment]
Fixed Via https://github.com/rebornix/vscode-project-snippet/commit/8e6deebf4eca402061f5571bcdea69a5ec65fab3
