### ISSUE TITLE
Documentation or tutorial

### ISSUE THREAD

**Issue by AleksandarAleksandrov** [rebornix/vscode-project-snippet#5]
It would be awesome if you can add some tutorial for working with the extension and some sample code snipets :)

**Comment by rebornix** [comment]
@AleksandarAleksandrov I wrote a short blog post for you to ramp up https://medium.com/@rebornix/share-snippets-with-your-team-in-vs-code-817801e853fb#.3y9px5rma . Let me know what's missing there :)

**Comment by thongdong7** [comment]
Should we add it to the README?

**Comment by rebornix** [comment]
You are right, readme is a better place for it :)

**Comment by thongdong7** [comment]
Okie, let me create a PR for this.
