### ISSUE TITLE
Does not find my snippets (made with tabs)

### ISSUE THREAD

**Issue by Knaackee** [rebornix/vscode-project-snippet#6]
Looks like there is problem parsing the snippet file 

The following works:

```
{
"My Snippet": {
"prefix": "mySnippet",
"body": ["test snippet"],
"description": "test"
}
}

```
The following doesnt work. (made with 1 tab per indentation).

```
{
	"My Snippet": {
		"prefix": "mySnippet",
		"body": ["test snippet"],
		"description": "test"
	}
}

```

**Comment by rebornix** [comment]
Hey @Knaackee may I ask what version are you using?

**Comment by thongdong7** [comment]
I have the same issue (version 0.4.0). After debug, I figured out that it happen because the following line

```javascript
jsonString = snippetFileContent.replace(/[\t]/g, "\\t");
```

@rebornix I could create a PR to fix this.
