### ISSUE TITLE
Show alert when could not parse the snippets file

### ISSUE THREAD

**Issue by thongdong7** [rebornix/vscode-project-snippet#9]
Currently, when could not parse snippet file, the plugin ignore it. It should show an error instead

**Comment by rebornix** [comment]
@thongdong7 the reason I didn't do that was when users are editing the snippet file, the file is incomplete/broken most of the time, and you have no idea when is the time users finish the editing. I'm open to showing tip/suggestion of parsing error to users but I'm against to use the Information or Error Popup message. Maybe putting it in status bar can be a proper solution? What do you think.

**Comment by thongdong7** [comment]
The validation only happen when user update or open the snippet file. So if we put on status bar, user lost space for this.

I think we could leverage the language server feature of VSCode to build a snippet validation. It helps highlight the error when user open the snippet file.

https://code.visualstudio.com/docs/extensions/example-language-server

Another kind of errors are:

* typo in `snippets` folder
* typo in `languageId.json`

For this kind of errors, I think a command to validate is more helpful.

**Comment by rebornix** [comment]
@thongdong7 actually we need to parse the content whenever it's saved. If users have auto-save, then editing the snippet file will lead to a bunch of incomplete snippet file.

But the idea of leveraging language server is really really inspiring, it can make this extension a realy product! Let me know if you want to give it a try as I already spent a lot of time in language server stuff in other places.

**Comment by thongdong7** [comment]
Okie, let me try.

**Comment by rebornix** [comment]
@thongdong7 yes it looks real neat, let's play with it first.
